apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deploy
  namespace: nexus-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "mkdir -p nexus-data ; chown -R 200:200 nexus-data "]
        volumeMounts:
          - mountPath: /nexus-data
            name: nexus-data-volume
      containers:
      - image: sonatype/nexus3:3.41.1
        name: nexus
        ports:
        - containerPort: 8081
        - containerPort: 5000
        volumeMounts:
          - mountPath: /nexus-data
            name: nexus-data-volume
      volumes:
        - name: nexus-data-volume
          persistentVolumeClaim:
            claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  namespace: nexus-ns
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    nodePort: 31010
    targetPort: 8081
    protocol: TCP
    name: http
  - port: 5000
    nodePort: 31011
    targetPort: 5000
    protocol: TCP
    name: docker 
  selector:
    app: nexus

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nexus-svc-load
#   namespace: nexus-ns
# spec:
#   type: LoadBalancer
#   selector:
#     app: nexus
#   ports:
#   - name: http
#     port: 8082
#     targetPort: 8081
